### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by themighty1** [iridium-browser/iridium-browser-dev#1]
The website states that "all our builds are reproducible". Does it mean they can be built deterministicaly and produce exact binaries? if so, where are the instructions for building deterministicaly?

**Comment by jengelh** [comment]
Delivered via the distro-typical repository mechanism:
https://dl.iridiumbrowser.de/openSUSE_13.2/src/
https://dl.iridiumbrowser.de/ubuntu/pool/main/i/iridium-browser/
Platforms without standards:
https://github.com/iridium-browser/iridium-browser-windows
https://github.com/iridium-browser/iridium-browser-osx

It is assumed that, if you are into the topic of reproducibility, you already know how to proceed. For example, feeding the .src.rpm from url 1 into an openSUSE 13.2 environment and rebuilding it ought to yield the same result, and the "build-compare" program, also in openSUSE and/or the Open Build Service, should return a match.

**Comment by medozas** [comment]
We've provided build instruction here: https://iridiumbrowser.de/development.html, additionally, you can find the full build instructions that are used in each sub repo (windows, osx, etc)
