### ISSUE TITLE
Build only works on Ubuntu

### ISSUE THREAD

**Issue by Chaz6** [iridium-browser/iridium-browser-dev#2]
I got as far as running `./src/build/install-build-deps.sh` only to get the following message:-
ERROR: Only Ubuntu 12.04 (precise), 14.04 (trusty),  14.10 (utopic) and 15.04 (vivid) are currently supported

Please provide generic Linux build instructions! Thanks.

**Comment by medozas** [comment]
We are working on some build instructions... For the moment, you can find everything in the corresponding src rpms for example at build.netitwork.net

**Comment by Chaz6** [comment]
Thanks for reply. I had a look at http://build.netitwork.net/ but there is just one file called overview.html.TEMPLATE which does not appear to contain any useful information about building.

**Comment by jengelh** [comment]
Closing old request.
(At present, build.netitwork.net is not meant for the public. All files we wish to release are on *.iridiumbrowser.de ; (s)rpms are on dl.iridiumbrowser.de)
