### ISSUE TITLE
https certificate expired?

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-dev#4]
Hi - to whom it may concern,

my Firefox 55.0.2 on Linux Mint 18.1 Cinnamon refuses to connect to the download page. Quote:

iridiumbrowser.de uses an invalid security certificate. The certificate expired on August 25, 2017, 8:45 AM. The current time is August 25, 2017, 9:08 PM.

[...]

Your connection is not secure

The owner of iridiumbrowser.de has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

Regards,
Frederik

**Comment by jengelh** [comment]
resolved / closing old ticket
