### ISSUE TITLE
SSL/TLS certificate expired for HTTPS

### ISSUE THREAD

**Issue by narcisgarcia** [iridium-browser/iridium-browser-dev#5]
This is since 2019.09.16

Err:21 https://downloads.iridiumbrowser.de/deb stable Release                  
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification.

Please, automate Letsencrypt certificates renewal.

**Comment by jengelh** [comment]
resolved / closing old ticket
